### ISSUE TITLE
summary methods produce output to console

### ISSUE THREAD

**Issue by pdmetcalfe** [harrysouthworth/texmex#26]
Many summary methods produce output to console; better practice is for summary methods to produce summary objects on which print methods are defined.

**Comment by harrysouthworth** [comment]
Ugh. Which ones? I assumed you were referring to summary.evmSim, but that does as you describe

**Comment by pdmetcalfe** [comment]
More than I felt cheerful about:

summary.texmexFamily, summary.MCS, summary.bootMCS, summary.migpd, summary.mex

(possibly among others)

**Comment by janetheffernan** [comment]
I'll get on this today.  Having a texmex spring clean here... THanks for point this out Paul,

**Comment by janetheffernan** [comment]
Just pushed with fix to this lot.
