### ISSUE TITLE
Error building testing vignette due to roxygen2 version

### ISSUE THREAD

**Issue by janetheffernan** [harrysouthworth/texmex#27]
I can't reproduce this on my machine but I get the following build error message from travis:

Quitting from lines 75-76 (test_texmex.Rnw) 
Error: processing vignette 'test_texmex.Rnw' failed with diagnostics:
'roxygen2' >= 5.0.0 must be installed for this functionality.
Execution halted
## 

it is triggered by the following line of code in the vignette

devtools::test("../../texmex",filter="plotrl.evm")

The change I have made is to use devtools for testing. which behaves as we want with the ignore on travis and ignore on cran  etc part of the tests.

**Comment by pdmetcalfe** [comment]
This seems to have gone away!
