### ISSUE TITLE
I can't apply anymore predict.mex on my mex data, why?

### ISSUE THREAD

**Issue by user241276** [harrysouthworth/texmex#28]
Dear colleagues,

I am working with the texmex package and I am not a statistician by definition.

I just realised that with R I cannot apply anymore the predict.mex function which worked perfectly no more than 1.5 months ago.

Is there a reason for this issue?
How can I overcome it?

I really need simulated data.

Thanks

**Comment by pdmetcalfe** [comment]
Does predict work i.e. use predict rather than predict.mex?

**Comment by user241276** [comment]
Thank you for your reply.

I just applied the same script with my desktop computer and 'predict.mex' works correctly. But still don't know why it doesn't with my laptop :-)

thanks.

**Comment by pdmetcalfe** [comment]
Please give the version number of texmex on your desktop and the version number of texmex on your laptop.

Does predict work rather than predict.mex (on your laptop)?

**Comment by user241276** [comment]
desktop version '2.1'
laptop version '2.3'

Yes, 'predict' works on my laptop and it returns a 'predict.mex' object.

I assume is everything ok
thanks

**Comment by pdmetcalfe** [comment]
yup.  FWIW old texmex was a bit lax about how it exported stuff, which is why this appeared when we tidied it up.
